pipeline {
    agent any
    stages {
        stage('install') {
            steps {
            	echo "install scrapy"
                sh 'pip install scrapy pysolr'
            }
        }
        stage('checkout') {
            steps {
            	echo "checkout scm"
                checkout scm
            }
        }
        stage('run spider') {
        	steps {
        		dir('event-spider-scrapy/event') {
        			sh 'scrapy crawl salarazzmatazz'
        		}
        	}
        }
    }
}