pipeline {
    agent any
    stages {
        stage('install') {
            steps {
                sh 'pip install scrapy'
            }
        }
        stage('run spider') {
        	steps {
        		dir event-spider-scrapy/event
        		sh 'scrapy crawl salarazzmatazz'
        	}
        }
    }
}